((0 uniq ""
  ((1 ins 4) (2 ins 4) (3 ins 4) (4 ins 4) (5 ins 4) (6 ins 4) (7 ins 4)
   (8 ins 4) (9 ins 4) (10 ins 4) (11 ins 4) (12 ins 4) (13 ins 4) (14 ins 6)
   (15 ins 6) (16 ins 6) (17 ins 6) (18 ins 6) (19 ins 6) (20 ins 6)
   (21 ins 6) (22 ins 6) (23 ins 6) (24 ins 6) (25 ins 6) (26 ins 6)
   (27 ins 6) (28 ins 6) (29 ins 6) (30 ins 6) (31 ins 6) (32 ins 6)
   (33 ins 6) (34 ins 6) (35 ins 6) (36 ins 6) (37 ins 6))
  () -1 0)
 (1 uniq "move 3 , 2 "
  ((0 del 4) (2 sub 2) (3 sub 1) (4 sub 2) (5 sub 2) (6 sub 1) (7 sub 2)
   (8 sub 2) (9 sub 1) (10 sub 2) (11 sub 2) (12 sub 2) (13 sub 2) (18 ins 2)
   (38 ins 4) (42 ins 4))
  () -1 0)
 (2 uniq "move 2 , 3 "
  ((0 del 4) (1 sub 2) (3 sub 2) (4 sub 1) (5 sub 2) (6 sub 2) (7 sub 1)
   (8 sub 2) (9 sub 2) (10 sub 2) (11 sub 2) (12 sub 2) (13 sub 2) (14 ins 2)
   (19 ins 2) (39 ins 4) (40 ins 4) (43 ins 4) (44 ins 4))
  () -1 0)
 (3 uniq "move 5 , 2 "
  ((0 del 4) (1 sub 1) (2 sub 2) (4 sub 2) (5 sub 2) (6 sub 1) (7 sub 2)
   (8 sub 2) (9 sub 2) (10 sub 2) (11 sub 1) (12 sub 2) (13 sub 2) (17 ins 2)
   (20 ins 2))
  () -1 0)
 (4 uniq "move 4 , 3 "
  ((0 del 4) (1 sub 2) (2 sub 1) (3 sub 2) (5 sub 1) (6 sub 2) (7 sub 1)
   (8 sub 2) (9 sub 2) (10 sub 2) (11 sub 2) (12 sub 2) (13 sub 2) (21 ins 2)
   (30 ins 2))
  ((14 nul 3)) -1 0)
 (5 uniq "move 4 , 4 "
  ((0 del 4) (1 sub 2) (2 sub 2) (3 sub 2) (4 sub 1) (6 sub 2) (7 sub 2)
   (8 sub 1) (9 sub 2) (10 sub 1) (11 sub 2) (12 sub 2) (13 sub 2))
  ((15 nul 3)) -1 0)
 (6 uniq "move ul , 2 "
  ((0 del 4) (1 sub 1) (2 sub 2) (3 sub 1) (4 sub 2) (5 sub 2) (7 sub 2)
   (8 sub 2) (9 sub 2) (10 sub 1) (11 sub 2) (12 sub 2) (13 sub 1))
  () -1 0)
 (7 uniq "move ua , 3 "
  ((0 del 4) (1 sub 2) (2 sub 1) (3 sub 2) (4 sub 1) (5 sub 2) (6 sub 2)
   (8 sub 1) (9 sub 2) (10 sub 2) (11 sub 2) (12 sub 1) (13 sub 2) (25 ins 2)
   (29 ins 2) (36 ins 2))
  () -1 0)
 (8 uniq "move ua , 4 "
  ((0 del 4) (1 sub 2) (2 sub 2) (3 sub 2) (4 sub 2) (5 sub 1) (6 sub 2)
   (7 sub 1) (9 sub 2) (10 sub 1) (11 sub 2) (12 sub 1) (13 sub 2) (25 ins 2)
   (32 ins 2) (37 ins 2))
  ((16 nul 3)) -1 0)
 (9 uniq "move 3 , ul "
  ((0 del 4) (1 sub 1) (2 sub 2) (3 sub 2) (4 sub 2) (5 sub 2) (6 sub 2)
   (7 sub 2) (8 sub 2) (10 sub 2) (11 sub 1) (12 sub 1) (13 sub 1) (24 ins 2)
   (42 ins 4) (44 ins 4))
  () -1 0)
 (10 uniq "move ul , 4 "
  ((0 del 4) (1 sub 2) (2 sub 2) (3 sub 2) (4 sub 2) (5 sub 1) (6 sub 1)
   (7 sub 2) (8 sub 1) (9 sub 2) (11 sub 2) (12 sub 2) (13 sub 1))
  ((13 sub 1)) -1 0)
 (11 uniq "move 5 , ul "
  ((0 del 4) (1 sub 2) (2 sub 2) (3 sub 1) (4 sub 2) (5 sub 2) (6 sub 2)
   (7 sub 2) (8 sub 2) (9 sub 1) (10 sub 2) (12 sub 1) (13 sub 1) (34 ins 2))
  () -1 0)
 (12 uniq "move ua , ul "
  ((0 del 4) (1 sub 2) (2 sub 2) (3 sub 2) (4 sub 2) (5 sub 2) (6 sub 2)
   (7 sub 1) (8 sub 1) (9 sub 1) (10 sub 2) (11 sub 1) (13 sub 1) (35 ins 2)
   (36 ins 2) (37 ins 2))
  ((24 nul 3)) -1 0)
 (13 equiv "move ul , ul "
  ((0 del 4) (1 sub 2) (2 sub 2) (3 sub 2) (4 sub 2) (5 sub 2) (6 sub 1)
   (7 sub 2) (8 sub 2) (9 sub 1) (10 sub 1) (11 sub 1) (12 sub 1))
  () 10 0)
 (14 equiv "move 2 * 2 , 3 "
  ((0 del 6) (2 del 2) (15 sub 1) (16 sub 2) (17 sub 3) (24 sub 2) (39 ins 2)
   (43 ins 2))
  () 4 0)
 (15 equiv "move 2 * 2 , 4 "
  ((0 del 6) (14 sub 1) (16 sub 1) (24 sub 2) (28 sub 3)) () 5 0)
 (16 equiv "move 2 * 3 , 4 "
  ((0 del 6) (14 sub 2) (15 sub 1) (19 sub 3) (24 sub 1) (25 sub 3)
   (28 sub 3))
  () 8 0)
 (17 uniq "move 5 , 2 / 3 "
  ((0 del 6) (3 del 2) (14 sub 3) (18 sub 2) (19 sub 3) (20 sub 1) (21 sub 3)
   (22 sub 3) (23 sub 2) (25 sub 3) (26 sub 2) (27 sub 3) (28 sub 3)
   (29 sub 3) (30 sub 2) (31 sub 3) (32 sub 3) (33 sub 3) (34 sub 2)
   (35 sub 3) (36 sub 2) (37 sub 3))
  () -1 0)
 (18 uniq "move 3 , 2 / 5 "
  ((0 del 6) (1 del 2) (17 sub 2) (19 sub 2) (20 sub 1) (21 sub 2) (22 sub 1)
   (23 sub 2) (25 sub 3) (26 sub 1) (27 sub 3) (28 sub 3) (29 sub 2)
   (30 sub 3) (31 sub 2) (32 sub 2) (33 sub 2) (34 sub 2) (35 sub 3)
   (36 sub 3) (37 sub 3) (38 ins 2))
  () -1 0)
 (19 uniq "move 2 , 3 / 5 "
  ((0 del 6) (2 del 2) (16 sub 3) (17 sub 3) (18 sub 2) (20 sub 2) (21 sub 1)
   (22 sub 2) (23 sub 2) (24 sub 3) (25 sub 2) (26 sub 2) (27 sub 3)
   (28 sub 2) (29 sub 1) (30 sub 3) (31 sub 1) (32 sub 2) (33 sub 2)
   (34 sub 2) (35 sub 3) (36 sub 3) (37 sub 3) (39 ins 2) (40 ins 2))
  () -1 0)
 (20 uniq "move 5 , 2 / 5 "
  ((0 del 6) (3 del 2) (17 sub 1) (18 sub 1) (19 sub 2) (21 sub 2) (22 sub 2)
   (23 sub 1) (25 sub 3) (26 sub 1) (27 sub 3) (28 sub 3) (29 sub 2)
   (30 sub 3) (31 sub 2) (32 sub 2) (33 sub 2) (34 sub 1) (35 sub 3)
   (36 sub 3) (37 sub 3))
  () -1 0)
 (21 uniq "move 4 , 3 / 5 "
  ((0 del 6) (4 del 2) (17 sub 3) (18 sub 2) (19 sub 1) (20 sub 2) (22 sub 2)
   (23 sub 2) (25 sub 2) (26 sub 2) (27 sub 2) (28 sub 3) (29 sub 1)
   (30 sub 2) (31 sub 2) (32 sub 2) (33 sub 1) (34 sub 2) (35 sub 3)
   (36 sub 3) (37 sub 3))
  ((39 nul 3)) -1 0)
 (22 uniq "move 3 , 4 / 5 "
  ((0 del 6) (17 sub 3) (18 sub 1) (19 sub 2) (20 sub 2) (21 sub 2)
   (23 sub 1) (25 sub 3) (26 sub 2) (27 sub 3) (28 sub 3) (29 sub 2)
   (30 sub 3) (31 sub 2) (32 sub 1) (33 sub 2) (34 sub 2) (35 sub 3)
   (36 sub 3) (37 sub 3))
  () -1 0)
 (23 uniq "move 5 , 4 / 5 "
  ((0 del 6) (17 sub 2) (18 sub 2) (19 sub 2) (20 sub 1) (21 sub 2)
   (22 sub 1) (25 sub 3) (26 sub 2) (27 sub 3) (28 sub 3) (29 sub 2)
   (30 sub 3) (31 sub 2) (32 sub 1) (33 sub 2) (34 sub 1) (35 sub 3)
   (36 sub 3) (37 sub 3))
  () -1 0)
 (24 equiv "move 2 * 3 , ul "
  ((0 del 6) (9 del 2) (14 sub 2) (15 sub 2) (16 sub 1) (19 sub 3) (42 ins 2)
   (44 ins 2))
  () 12 0)
 (25 uniq "move ua , 3 / 4 "
  ((0 del 6) (7 del 2) (8 del 2) (16 sub 3) (17 sub 3) (18 sub 3) (19 sub 2)
   (20 sub 3) (21 sub 2) (22 sub 3) (23 sub 3) (26 sub 2) (27 sub 3)
   (28 sub 2) (29 sub 1) (30 sub 3) (31 sub 3) (32 sub 2) (33 sub 3)
   (34 sub 3) (35 sub 2) (36 sub 2) (37 sub 1))
  () -1 0)
 (26 uniq "move ua , 2 / 5 "
  ((0 del 6) (17 sub 2) (18 sub 1) (19 sub 2) (20 sub 1) (21 sub 2)
   (22 sub 2) (23 sub 2) (25 sub 2) (27 sub 3) (28 sub 3) (29 sub 1)
   (30 sub 3) (31 sub 2) (32 sub 1) (33 sub 2) (34 sub 2) (35 sub 2)
   (36 sub 2) (37 sub 2))
  ((38 nul 3)) -1 0)
 (27 uniq "move 4 , ul / 2 "
  ((0 del 6) (17 sub 3) (18 sub 3) (19 sub 3) (20 sub 3) (21 sub 2)
   (22 sub 3) (23 sub 3) (25 sub 3) (26 sub 3) (28 sub 2) (29 sub 3)
   (30 sub 1) (31 sub 2) (32 sub 3) (33 sub 1) (34 sub 2) (35 sub 1)
   (36 sub 2) (37 sub 2))
  ((41 nul 3)) -1 0)
 (28 uniq "move 2 , ul / 4 "
  ((0 del 6) (15 sub 3) (16 sub 3) (17 sub 3) (18 sub 3) (19 sub 2)
   (20 sub 3) (21 sub 3) (22 sub 3) (23 sub 3) (25 sub 2) (26 sub 3)
   (27 sub 2) (29 sub 3) (30 sub 2) (31 sub 1) (32 sub 3) (33 sub 2)
   (34 sub 2) (35 sub 2) (36 sub 2) (37 sub 1))
  ((31 sub 1)) -1 0)
 (29 uniq "move ua , 3 / 5 "
  ((0 del 6) (7 del 2) (17 sub 3) (18 sub 2) (19 sub 1) (20 sub 2) (21 sub 1)
   (22 sub 2) (23 sub 2) (25 sub 1) (26 sub 1) (27 sub 3) (28 sub 3)
   (30 sub 3) (31 sub 2) (32 sub 1) (33 sub 2) (34 sub 2) (35 sub 2)
   (36 sub 2) (37 sub 2))
  ((40 nul 3)) -1 0)
 (30 uniq "move 4 , ul / 3 "
  ((0 del 6) (4 del 2) (17 sub 2) (18 sub 3) (19 sub 3) (20 sub 3) (21 sub 2)
   (22 sub 3) (23 sub 3) (25 sub 3) (26 sub 3) (27 sub 1) (28 sub 2)
   (29 sub 3) (31 sub 2) (32 sub 3) (33 sub 1) (34 sub 2) (35 sub 2)
   (36 sub 1) (37 sub 2))
  ((43 nul 3)) -1 0)
 (31 equiv "move 2 , ul / 5 "
  ((0 del 6) (17 sub 3) (18 sub 2) (19 sub 1) (20 sub 2) (21 sub 2)
   (22 sub 2) (23 sub 2) (25 sub 3) (26 sub 2) (27 sub 2) (28 sub 1)
   (29 sub 2) (30 sub 2) (32 sub 2) (33 sub 1) (34 sub 1) (35 sub 2)
   (36 sub 2) (37 sub 2) (45 ins 2))
  () 28 0)
 (32 uniq "move ua , 4 / 5 "
  ((0 del 6) (8 del 2) (17 sub 3) (18 sub 2) (19 sub 2) (20 sub 2) (21 sub 2)
   (22 sub 1) (23 sub 1) (25 sub 2) (26 sub 1) (27 sub 3) (28 sub 3)
   (29 sub 1) (30 sub 3) (31 sub 2) (33 sub 2) (34 sub 2) (35 sub 2)
   (36 sub 2) (37 sub 2))
  () -1 0)
 (33 uniq "move 4 , ul / 5 "
  ((0 del 6) (17 sub 3) (18 sub 2) (19 sub 2) (20 sub 2) (21 sub 1)
   (22 sub 2) (23 sub 2) (25 sub 3) (26 sub 2) (27 sub 1) (28 sub 2)
   (29 sub 2) (30 sub 1) (31 sub 1) (32 sub 2) (34 sub 1) (35 sub 2)
   (36 sub 2) (37 sub 2))
  ((45 nul 3)) -1 0)
 (34 uniq "move 5 , ul / 5 "
  ((0 del 6) (11 del 2) (17 sub 2) (18 sub 2) (19 sub 2) (20 sub 1)
   (21 sub 2) (22 sub 2) (23 sub 1) (25 sub 3) (26 sub 2) (27 sub 2)
   (28 sub 2) (29 sub 2) (30 sub 2) (31 sub 1) (32 sub 2) (33 sub 1)
   (35 sub 2) (36 sub 2) (37 sub 2))
  () -1 0)
 (35 uniq "move ua , ul / 2 "
  ((0 del 6) (12 del 2) (17 sub 3) (18 sub 3) (19 sub 3) (20 sub 3)
   (21 sub 3) (22 sub 3) (23 sub 3) (25 sub 2) (26 sub 2) (27 sub 1)
   (28 sub 2) (29 sub 2) (30 sub 2) (31 sub 2) (32 sub 2) (33 sub 2)
   (34 sub 2) (36 sub 1) (37 sub 1))
  ((42 nul 3)) -1 0)
 (36 uniq "move ua , ul / 3 "
  ((0 del 6) (7 del 2) (12 del 2) (17 sub 2) (18 sub 3) (19 sub 3) (20 sub 3)
   (21 sub 3) (22 sub 3) (23 sub 3) (25 sub 2) (26 sub 2) (27 sub 2)
   (28 sub 2) (29 sub 2) (30 sub 1) (31 sub 2) (32 sub 2) (33 sub 2)
   (34 sub 2) (35 sub 1) (37 sub 1))
  ((44 nul 3)) -1 0)
 (37 uniq "move ua , ul / 4 "
  ((0 del 6) (8 del 2) (12 del 2) (17 sub 3) (18 sub 3) (19 sub 3) (20 sub 3)
   (21 sub 3) (22 sub 3) (23 sub 3) (25 sub 1) (26 sub 2) (27 sub 2)
   (28 sub 1) (29 sub 2) (30 sub 2) (31 sub 2) (32 sub 2) (33 sub 2)
   (34 sub 2) (35 sub 1) (36 sub 1))
  () -1 0)
 (38 equiv "move 2 * 3 , 2 / 5 "
  ((1 del 4) (18 del 2) (39 sub 2) (40 sub 1) (41 sub 3) (42 sub 2)
   (43 sub 3) (44 sub 2) (45 sub 2))
  () 26 0)
 (39 equiv "move 2 * 2 , 3 / 5 "
  ((2 del 4) (14 del 2) (19 del 2) (38 sub 2) (40 sub 1) (41 sub 2)
   (42 sub 3) (43 sub 2) (44 sub 3) (45 sub 1))
  () 21 0)
 (40 equiv "move 2 * 3 , 3 / 5 "
  ((2 del 4) (19 del 2) (38 sub 1) (39 sub 1) (41 sub 3) (42 sub 2)
   (43 sub 3) (44 sub 2) (45 sub 2))
  () 29 0)
 (41 equiv "move 2 * 2 , ul / 2 "
  ((38 sub 3) (39 sub 2) (40 sub 3) (42 sub 1) (43 sub 1) (44 sub 2)
   (45 sub 1))
  () 27 0)
 (42 equiv "move 2 * 3 , ul / 2 "
  ((1 del 4) (9 del 4) (24 del 2) (38 sub 2) (39 sub 3) (40 sub 2) (41 sub 1)
   (43 sub 2) (44 sub 1) (45 sub 2))
  () 35 0)
 (43 equiv "move 2 * 2 , ul / 3 "
  ((2 del 4) (14 del 2) (38 sub 3) (39 sub 2) (40 sub 3) (41 sub 1)
   (42 sub 2) (44 sub 1) (45 sub 1))
  () 30 0)
 (44 equiv "move 2 * 3 , ul / 3 "
  ((2 del 4) (9 del 4) (24 del 2) (38 sub 2) (39 sub 3) (40 sub 2) (41 sub 2)
   (42 sub 1) (43 sub 1) (45 sub 2))
  () 36 0)
 (45 equiv "move 2 * 2 , ul / 5 "
  ((31 del 2) (38 sub 2) (39 sub 1) (40 sub 2) (41 sub 1) (42 sub 2)
   (43 sub 1) (44 sub 2))
  () 33 0))