open Ctypes

(* This Types_generated module is an instantiation of the Types
   functor defined in the type_description.ml file. It's generated by
   a C program that Dune creates and runs behind the scenes. *)
module Types = Types_generated

module Functions (F : Ctypes.FOREIGN) = struct
	open F

	type imgdb = unit ptr
	let imgdb : imgdb typ = ptr void

	let simdb_allocate = foreign "simdb_allocate" (int @-> returning imgdb)
	let simdb_free = foreign "simdb_free" (imgdb @-> returning void)
	let simdb_set = foreign "simdb_set" 
		(imgdb @-> int @-> ptr void @-> returning void)
	let simdb_query = foreign "simdb_query" 
		(imgdb @-> ptr void @-> ptr void @-> ptr void @-> returning void)

end
